case_1_input = {
    "instructions": [
        "deal",
        "cut 13",
        "cut 13",
        "shuffle",
        "shuffle",
        "shuffle",
        "shuffle",
        "shuffle",
        "shuffle",
        "shuffle",
        "shuffle",
        "cut 13",
        "cut 13",
        "deal",
    ],
    "deck_size": 52,
    "card": 6,
    "actual": 6,
}

case_2_input = {
    "instructions": [
        "shuffle",
        "shuffle",
        "shuffle",
        "cut 133",
        "shuffle",
        "cut 2024",
        "shuffle",
        "shuffle",
        "cut 2",
        "shuffle",
        "cut 2500",
        "shuffle",
        "cut 1999",
        "shuffle",
        "cut 10",
        "deal",
    ],
    "deck_size": 1000000,
    "card": 54321,
    "actual": 274924,
}

